// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/secret"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/team"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

// Secret is the model entity for the Secret schema.
type Secret struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SecretPrefix holds the value of the "secret_prefix" field.
	SecretPrefix string `json:"secret_prefix,omitempty"`
	// SecretLength holds the value of the "secret_length" field.
	SecretLength int `json:"secret_length,omitempty"`
	// SecretMaskPrefix holds the value of the "secret_mask_prefix" field.
	SecretMaskPrefix string `json:"secret_mask_prefix,omitempty"`
	// SecretMaskSuffix holds the value of the "secret_mask_suffix" field.
	SecretMaskSuffix string `json:"secret_mask_suffix,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID uuid.UUID `json:"team_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Hosts holds the value of the "hosts" field.
	Hosts pq.StringArray `json:"hosts,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecretQuery when eager-loading is set.
	Edges        SecretEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SecretEdges holds the relations/edges for other nodes in the graph.
type SecretEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecretEdges) TeamOrErr() (*Team, error) {
	if e.loadedTypes[0] {
		if e.Team == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: team.Label}
		}
		return e.Team, nil
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Secret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case secret.FieldHosts:
			values[i] = new(pq.StringArray)
		case secret.FieldSecretLength:
			values[i] = new(sql.NullInt64)
		case secret.FieldSecretPrefix, secret.FieldSecretMaskPrefix, secret.FieldSecretMaskSuffix, secret.FieldName:
			values[i] = new(sql.NullString)
		case secret.FieldCreatedAt, secret.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case secret.FieldID, secret.FieldTeamID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Secret fields.
func (s *Secret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case secret.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				s.ID = *value
			}
		case secret.FieldSecretPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_prefix", values[i])
			} else if value.Valid {
				s.SecretPrefix = value.String
			}
		case secret.FieldSecretLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field secret_length", values[i])
			} else if value.Valid {
				s.SecretLength = int(value.Int64)
			}
		case secret.FieldSecretMaskPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_mask_prefix", values[i])
			} else if value.Valid {
				s.SecretMaskPrefix = value.String
			}
		case secret.FieldSecretMaskSuffix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_mask_suffix", values[i])
			} else if value.Valid {
				s.SecretMaskSuffix = value.String
			}
		case secret.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case secret.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = new(time.Time)
				*s.UpdatedAt = value.Time
			}
		case secret.FieldTeamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value != nil {
				s.TeamID = *value
			}
		case secret.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case secret.FieldHosts:
			if value, ok := values[i].(*pq.StringArray); !ok {
				return fmt.Errorf("unexpected type %T for field hosts", values[i])
			} else if value != nil {
				s.Hosts = *value
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Secret.
// This includes values selected through modifiers, order, etc.
func (s *Secret) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the Secret entity.
func (s *Secret) QueryTeam() *TeamQuery {
	return NewSecretClient(s.config).QueryTeam(s)
}

// Update returns a builder for updating this Secret.
// Note that you need to call Secret.Unwrap() before calling this method if this Secret
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Secret) Update() *SecretUpdateOne {
	return NewSecretClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Secret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Secret) Unwrap() *Secret {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("models: Secret is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Secret) String() string {
	var builder strings.Builder
	builder.WriteString("Secret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("secret_prefix=")
	builder.WriteString(s.SecretPrefix)
	builder.WriteString(", ")
	builder.WriteString("secret_length=")
	builder.WriteString(fmt.Sprintf("%v", s.SecretLength))
	builder.WriteString(", ")
	builder.WriteString("secret_mask_prefix=")
	builder.WriteString(s.SecretMaskPrefix)
	builder.WriteString(", ")
	builder.WriteString("secret_mask_suffix=")
	builder.WriteString(s.SecretMaskSuffix)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := s.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", s.TeamID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("hosts=")
	builder.WriteString(fmt.Sprintf("%v", s.Hosts))
	builder.WriteByte(')')
	return builder.String()
}

// Secrets is a parsable slice of Secret.
type Secrets []*Secret
