// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/internal"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/predicate"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/team"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/teamsecret"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

// TeamSecretUpdate is the builder for updating TeamSecret entities.
type TeamSecretUpdate struct {
	config
	hooks     []Hook
	mutation  *TeamSecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TeamSecretUpdate builder.
func (tsu *TeamSecretUpdate) Where(ps ...predicate.TeamSecret) *TeamSecretUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetUpdatedAt sets the "updated_at" field.
func (tsu *TeamSecretUpdate) SetUpdatedAt(t time.Time) *TeamSecretUpdate {
	tsu.mutation.SetUpdatedAt(t)
	return tsu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsu *TeamSecretUpdate) SetNillableUpdatedAt(t *time.Time) *TeamSecretUpdate {
	if t != nil {
		tsu.SetUpdatedAt(*t)
	}
	return tsu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tsu *TeamSecretUpdate) ClearUpdatedAt() *TeamSecretUpdate {
	tsu.mutation.ClearUpdatedAt()
	return tsu
}

// SetTeamID sets the "team_id" field.
func (tsu *TeamSecretUpdate) SetTeamID(u uuid.UUID) *TeamSecretUpdate {
	tsu.mutation.SetTeamID(u)
	return tsu
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (tsu *TeamSecretUpdate) SetNillableTeamID(u *uuid.UUID) *TeamSecretUpdate {
	if u != nil {
		tsu.SetTeamID(*u)
	}
	return tsu
}

// SetName sets the "name" field.
func (tsu *TeamSecretUpdate) SetName(s string) *TeamSecretUpdate {
	tsu.mutation.SetName(s)
	return tsu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tsu *TeamSecretUpdate) SetNillableName(s *string) *TeamSecretUpdate {
	if s != nil {
		tsu.SetName(*s)
	}
	return tsu
}

// SetHosts sets the "hosts" field.
func (tsu *TeamSecretUpdate) SetHosts(pa pq.StringArray) *TeamSecretUpdate {
	tsu.mutation.SetHosts(pa)
	return tsu
}

// SetTeam sets the "team" edge to the Team entity.
func (tsu *TeamSecretUpdate) SetTeam(t *Team) *TeamSecretUpdate {
	return tsu.SetTeamID(t.ID)
}

// Mutation returns the TeamSecretMutation object of the builder.
func (tsu *TeamSecretUpdate) Mutation() *TeamSecretMutation {
	return tsu.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (tsu *TeamSecretUpdate) ClearTeam() *TeamSecretUpdate {
	tsu.mutation.ClearTeam()
	return tsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TeamSecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TeamSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TeamSecretUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TeamSecretUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsu *TeamSecretUpdate) check() error {
	if _, ok := tsu.mutation.TeamID(); tsu.mutation.TeamCleared() && !ok {
		return errors.New(`models: clearing a required unique edge "TeamSecret.team"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsu *TeamSecretUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamSecretUpdate {
	tsu.modifiers = append(tsu.modifiers, modifiers...)
	return tsu
}

func (tsu *TeamSecretUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamsecret.Table, teamsecret.Columns, sqlgraph.NewFieldSpec(teamsecret.FieldID, field.TypeUUID))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.UpdatedAt(); ok {
		_spec.SetField(teamsecret.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsu.mutation.UpdatedAtCleared() {
		_spec.ClearField(teamsecret.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := tsu.mutation.Name(); ok {
		_spec.SetField(teamsecret.FieldName, field.TypeString, value)
	}
	if value, ok := tsu.mutation.Hosts(); ok {
		_spec.SetField(teamsecret.FieldHosts, field.TypeOther, value)
	}
	if tsu.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamsecret.TeamTable,
			Columns: []string{teamsecret.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = tsu.schemaConfig.TeamSecret
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamsecret.TeamTable,
			Columns: []string{teamsecret.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = tsu.schemaConfig.TeamSecret
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = tsu.schemaConfig.TeamSecret
	ctx = internal.NewSchemaConfigContext(ctx, tsu.schemaConfig)
	_spec.AddModifiers(tsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TeamSecretUpdateOne is the builder for updating a single TeamSecret entity.
type TeamSecretUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TeamSecretMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (tsuo *TeamSecretUpdateOne) SetUpdatedAt(t time.Time) *TeamSecretUpdateOne {
	tsuo.mutation.SetUpdatedAt(t)
	return tsuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsuo *TeamSecretUpdateOne) SetNillableUpdatedAt(t *time.Time) *TeamSecretUpdateOne {
	if t != nil {
		tsuo.SetUpdatedAt(*t)
	}
	return tsuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tsuo *TeamSecretUpdateOne) ClearUpdatedAt() *TeamSecretUpdateOne {
	tsuo.mutation.ClearUpdatedAt()
	return tsuo
}

// SetTeamID sets the "team_id" field.
func (tsuo *TeamSecretUpdateOne) SetTeamID(u uuid.UUID) *TeamSecretUpdateOne {
	tsuo.mutation.SetTeamID(u)
	return tsuo
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (tsuo *TeamSecretUpdateOne) SetNillableTeamID(u *uuid.UUID) *TeamSecretUpdateOne {
	if u != nil {
		tsuo.SetTeamID(*u)
	}
	return tsuo
}

// SetName sets the "name" field.
func (tsuo *TeamSecretUpdateOne) SetName(s string) *TeamSecretUpdateOne {
	tsuo.mutation.SetName(s)
	return tsuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tsuo *TeamSecretUpdateOne) SetNillableName(s *string) *TeamSecretUpdateOne {
	if s != nil {
		tsuo.SetName(*s)
	}
	return tsuo
}

// SetHosts sets the "hosts" field.
func (tsuo *TeamSecretUpdateOne) SetHosts(pa pq.StringArray) *TeamSecretUpdateOne {
	tsuo.mutation.SetHosts(pa)
	return tsuo
}

// SetTeam sets the "team" edge to the Team entity.
func (tsuo *TeamSecretUpdateOne) SetTeam(t *Team) *TeamSecretUpdateOne {
	return tsuo.SetTeamID(t.ID)
}

// Mutation returns the TeamSecretMutation object of the builder.
func (tsuo *TeamSecretUpdateOne) Mutation() *TeamSecretMutation {
	return tsuo.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (tsuo *TeamSecretUpdateOne) ClearTeam() *TeamSecretUpdateOne {
	tsuo.mutation.ClearTeam()
	return tsuo
}

// Where appends a list predicates to the TeamSecretUpdate builder.
func (tsuo *TeamSecretUpdateOne) Where(ps ...predicate.TeamSecret) *TeamSecretUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TeamSecretUpdateOne) Select(field string, fields ...string) *TeamSecretUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TeamSecret entity.
func (tsuo *TeamSecretUpdateOne) Save(ctx context.Context) (*TeamSecret, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TeamSecretUpdateOne) SaveX(ctx context.Context) *TeamSecret {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TeamSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TeamSecretUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsuo *TeamSecretUpdateOne) check() error {
	if _, ok := tsuo.mutation.TeamID(); tsuo.mutation.TeamCleared() && !ok {
		return errors.New(`models: clearing a required unique edge "TeamSecret.team"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tsuo *TeamSecretUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamSecretUpdateOne {
	tsuo.modifiers = append(tsuo.modifiers, modifiers...)
	return tsuo
}

func (tsuo *TeamSecretUpdateOne) sqlSave(ctx context.Context) (_node *TeamSecret, err error) {
	if err := tsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamsecret.Table, teamsecret.Columns, sqlgraph.NewFieldSpec(teamsecret.FieldID, field.TypeUUID))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "TeamSecret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamsecret.FieldID)
		for _, f := range fields {
			if !teamsecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != teamsecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.UpdatedAt(); ok {
		_spec.SetField(teamsecret.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(teamsecret.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := tsuo.mutation.Name(); ok {
		_spec.SetField(teamsecret.FieldName, field.TypeString, value)
	}
	if value, ok := tsuo.mutation.Hosts(); ok {
		_spec.SetField(teamsecret.FieldHosts, field.TypeOther, value)
	}
	if tsuo.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamsecret.TeamTable,
			Columns: []string{teamsecret.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = tsuo.schemaConfig.TeamSecret
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamsecret.TeamTable,
			Columns: []string{teamsecret.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = tsuo.schemaConfig.TeamSecret
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = tsuo.schemaConfig.TeamSecret
	ctx = internal.NewSchemaConfigContext(ctx, tsuo.schemaConfig)
	_spec.AddModifiers(tsuo.modifiers...)
	_node = &TeamSecret{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamsecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
