// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/internal"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/predicate"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/team"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/teamsecret"
	"github.com/google/uuid"
)

// TeamSecretQuery is the builder for querying TeamSecret entities.
type TeamSecretQuery struct {
	config
	ctx        *QueryContext
	order      []teamsecret.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamSecret
	withTeam   *TeamQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamSecretQuery builder.
func (tsq *TeamSecretQuery) Where(ps ...predicate.TeamSecret) *TeamSecretQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TeamSecretQuery) Limit(limit int) *TeamSecretQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TeamSecretQuery) Offset(offset int) *TeamSecretQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TeamSecretQuery) Unique(unique bool) *TeamSecretQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TeamSecretQuery) Order(o ...teamsecret.OrderOption) *TeamSecretQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryTeam chains the current query on the "team" edge.
func (tsq *TeamSecretQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamsecret.Table, teamsecret.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, teamsecret.TeamTable, teamsecret.TeamColumn),
		)
		schemaConfig := tsq.schemaConfig
		step.To.Schema = schemaConfig.Team
		step.Edge.Schema = schemaConfig.TeamSecret
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamSecret entity from the query.
// Returns a *NotFoundError when no TeamSecret was found.
func (tsq *TeamSecretQuery) First(ctx context.Context) (*TeamSecret, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamsecret.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TeamSecretQuery) FirstX(ctx context.Context) *TeamSecret {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamSecret ID from the query.
// Returns a *NotFoundError when no TeamSecret ID was found.
func (tsq *TeamSecretQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamsecret.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TeamSecretQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamSecret entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamSecret entity is found.
// Returns a *NotFoundError when no TeamSecret entities are found.
func (tsq *TeamSecretQuery) Only(ctx context.Context) (*TeamSecret, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamsecret.Label}
	default:
		return nil, &NotSingularError{teamsecret.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TeamSecretQuery) OnlyX(ctx context.Context) *TeamSecret {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamSecret ID in the query.
// Returns a *NotSingularError when more than one TeamSecret ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TeamSecretQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamsecret.Label}
	default:
		err = &NotSingularError{teamsecret.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TeamSecretQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamSecrets.
func (tsq *TeamSecretQuery) All(ctx context.Context) ([]*TeamSecret, error) {
	ctx = setContextOp(ctx, tsq.ctx, "All")
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamSecret, *TeamSecretQuery]()
	return withInterceptors[[]*TeamSecret](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TeamSecretQuery) AllX(ctx context.Context) []*TeamSecret {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamSecret IDs.
func (tsq *TeamSecretQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, "IDs")
	if err = tsq.Select(teamsecret.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TeamSecretQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TeamSecretQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Count")
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TeamSecretQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TeamSecretQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TeamSecretQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Exist")
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("models: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TeamSecretQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamSecretQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TeamSecretQuery) Clone() *TeamSecretQuery {
	if tsq == nil {
		return nil
	}
	return &TeamSecretQuery{
		config:     tsq.config,
		ctx:        tsq.ctx.Clone(),
		order:      append([]teamsecret.OrderOption{}, tsq.order...),
		inters:     append([]Interceptor{}, tsq.inters...),
		predicates: append([]predicate.TeamSecret{}, tsq.predicates...),
		withTeam:   tsq.withTeam.Clone(),
		// clone intermediate query.
		sql:  tsq.sql.Clone(),
		path: tsq.path,
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TeamSecretQuery) WithTeam(opts ...func(*TeamQuery)) *TeamSecretQuery {
	query := (&TeamClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withTeam = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SecretPrefix string `json:"secret_prefix,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamSecret.Query().
//		GroupBy(teamsecret.FieldSecretPrefix).
//		Aggregate(models.Count()).
//		Scan(ctx, &v)
func (tsq *TeamSecretQuery) GroupBy(field string, fields ...string) *TeamSecretGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamSecretGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = teamsecret.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SecretPrefix string `json:"secret_prefix,omitempty"`
//	}
//
//	client.TeamSecret.Query().
//		Select(teamsecret.FieldSecretPrefix).
//		Scan(ctx, &v)
func (tsq *TeamSecretQuery) Select(fields ...string) *TeamSecretSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TeamSecretSelect{TeamSecretQuery: tsq}
	sbuild.label = teamsecret.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamSecretSelect configured with the given aggregations.
func (tsq *TeamSecretQuery) Aggregate(fns ...AggregateFunc) *TeamSecretSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TeamSecretQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("models: uninitialized interceptor (forgotten import models/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !teamsecret.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TeamSecretQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamSecret, error) {
	var (
		nodes       = []*TeamSecret{}
		_spec       = tsq.querySpec()
		loadedTypes = [1]bool{
			tsq.withTeam != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamSecret).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamSecret{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = tsq.schemaConfig.TeamSecret
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withTeam; query != nil {
		if err := tsq.loadTeam(ctx, query, nodes, nil,
			func(n *TeamSecret, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TeamSecretQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*TeamSecret, init func(*TeamSecret), assign func(*TeamSecret, *Team)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TeamSecret)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tsq *TeamSecretQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Schema = tsq.schemaConfig.TeamSecret
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	if len(tsq.modifiers) > 0 {
		_spec.Modifiers = tsq.modifiers
	}
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TeamSecretQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamsecret.Table, teamsecret.Columns, sqlgraph.NewFieldSpec(teamsecret.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamsecret.FieldID)
		for i := range fields {
			if fields[i] != teamsecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tsq.withTeam != nil {
			_spec.Node.AddColumnOnce(teamsecret.FieldTeamID)
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TeamSecretQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(teamsecret.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = teamsecret.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(tsq.schemaConfig.TeamSecret)
	ctx = internal.NewSchemaConfigContext(ctx, tsq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range tsq.modifiers {
		m(selector)
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tsq *TeamSecretQuery) Modify(modifiers ...func(s *sql.Selector)) *TeamSecretSelect {
	tsq.modifiers = append(tsq.modifiers, modifiers...)
	return tsq.Select()
}

// TeamSecretGroupBy is the group-by builder for TeamSecret entities.
type TeamSecretGroupBy struct {
	selector
	build *TeamSecretQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TeamSecretGroupBy) Aggregate(fns ...AggregateFunc) *TeamSecretGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TeamSecretGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, "GroupBy")
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamSecretQuery, *TeamSecretGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TeamSecretGroupBy) sqlScan(ctx context.Context, root *TeamSecretQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamSecretSelect is the builder for selecting fields of TeamSecret entities.
type TeamSecretSelect struct {
	*TeamSecretQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TeamSecretSelect) Aggregate(fns ...AggregateFunc) *TeamSecretSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TeamSecretSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, "Select")
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamSecretQuery, *TeamSecretSelect](ctx, tss.TeamSecretQuery, tss, tss.inters, v)
}

func (tss *TeamSecretSelect) sqlScan(ctx context.Context, root *TeamSecretQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tss *TeamSecretSelect) Modify(modifiers ...func(s *sql.Selector)) *TeamSecretSelect {
	tss.modifiers = append(tss.modifiers, modifiers...)
	return tss
}
