// Code generated by ent, DO NOT EDIT.

package models

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/internal"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/predicate"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/teamsecret"
)

// TeamSecretDelete is the builder for deleting a TeamSecret entity.
type TeamSecretDelete struct {
	config
	hooks    []Hook
	mutation *TeamSecretMutation
}

// Where appends a list predicates to the TeamSecretDelete builder.
func (tsd *TeamSecretDelete) Where(ps ...predicate.TeamSecret) *TeamSecretDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TeamSecretDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TeamSecretDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TeamSecretDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamsecret.Table, sqlgraph.NewFieldSpec(teamsecret.FieldID, field.TypeUUID))
	_spec.Node.Schema = tsd.schemaConfig.TeamSecret
	ctx = internal.NewSchemaConfigContext(ctx, tsd.schemaConfig)
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TeamSecretDeleteOne is the builder for deleting a single TeamSecret entity.
type TeamSecretDeleteOne struct {
	tsd *TeamSecretDelete
}

// Where appends a list predicates to the TeamSecretDelete builder.
func (tsdo *TeamSecretDeleteOne) Where(ps ...predicate.TeamSecret) *TeamSecretDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TeamSecretDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamsecret.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TeamSecretDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
