// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/team"
	"github.com/e2b-dev/infra/packages/shared/pkg/models/teamsecret"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

// TeamSecret is the model entity for the TeamSecret schema.
type TeamSecret struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SecretPrefix holds the value of the "secret_prefix" field.
	SecretPrefix string `json:"secret_prefix,omitempty"`
	// SecretLength holds the value of the "secret_length" field.
	SecretLength int `json:"secret_length,omitempty"`
	// SecretMaskPrefix holds the value of the "secret_mask_prefix" field.
	SecretMaskPrefix string `json:"secret_mask_prefix,omitempty"`
	// SecretMaskSuffix holds the value of the "secret_mask_suffix" field.
	SecretMaskSuffix string `json:"secret_mask_suffix,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID uuid.UUID `json:"team_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Hosts holds the value of the "hosts" field.
	Hosts pq.StringArray `json:"hosts,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamSecretQuery when eager-loading is set.
	Edges        TeamSecretEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamSecretEdges holds the relations/edges for other nodes in the graph.
type TeamSecretEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamSecretEdges) TeamOrErr() (*Team, error) {
	if e.loadedTypes[0] {
		if e.Team == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: team.Label}
		}
		return e.Team, nil
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamSecret) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamsecret.FieldHosts:
			values[i] = new(pq.StringArray)
		case teamsecret.FieldSecretLength:
			values[i] = new(sql.NullInt64)
		case teamsecret.FieldSecretPrefix, teamsecret.FieldSecretMaskPrefix, teamsecret.FieldSecretMaskSuffix, teamsecret.FieldName:
			values[i] = new(sql.NullString)
		case teamsecret.FieldCreatedAt, teamsecret.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case teamsecret.FieldID, teamsecret.FieldTeamID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamSecret fields.
func (ts *TeamSecret) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamsecret.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ts.ID = *value
			}
		case teamsecret.FieldSecretPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_prefix", values[i])
			} else if value.Valid {
				ts.SecretPrefix = value.String
			}
		case teamsecret.FieldSecretLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field secret_length", values[i])
			} else if value.Valid {
				ts.SecretLength = int(value.Int64)
			}
		case teamsecret.FieldSecretMaskPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_mask_prefix", values[i])
			} else if value.Valid {
				ts.SecretMaskPrefix = value.String
			}
		case teamsecret.FieldSecretMaskSuffix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_mask_suffix", values[i])
			} else if value.Valid {
				ts.SecretMaskSuffix = value.String
			}
		case teamsecret.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ts.CreatedAt = value.Time
			}
		case teamsecret.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ts.UpdatedAt = new(time.Time)
				*ts.UpdatedAt = value.Time
			}
		case teamsecret.FieldTeamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value != nil {
				ts.TeamID = *value
			}
		case teamsecret.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ts.Name = value.String
			}
		case teamsecret.FieldHosts:
			if value, ok := values[i].(*pq.StringArray); !ok {
				return fmt.Errorf("unexpected type %T for field hosts", values[i])
			} else if value != nil {
				ts.Hosts = *value
			}
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamSecret.
// This includes values selected through modifiers, order, etc.
func (ts *TeamSecret) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamSecret entity.
func (ts *TeamSecret) QueryTeam() *TeamQuery {
	return NewTeamSecretClient(ts.config).QueryTeam(ts)
}

// Update returns a builder for updating this TeamSecret.
// Note that you need to call TeamSecret.Unwrap() before calling this method if this TeamSecret
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *TeamSecret) Update() *TeamSecretUpdateOne {
	return NewTeamSecretClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the TeamSecret entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *TeamSecret) Unwrap() *TeamSecret {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("models: TeamSecret is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *TeamSecret) String() string {
	var builder strings.Builder
	builder.WriteString("TeamSecret(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ts.ID))
	builder.WriteString("secret_prefix=")
	builder.WriteString(ts.SecretPrefix)
	builder.WriteString(", ")
	builder.WriteString("secret_length=")
	builder.WriteString(fmt.Sprintf("%v", ts.SecretLength))
	builder.WriteString(", ")
	builder.WriteString("secret_mask_prefix=")
	builder.WriteString(ts.SecretMaskPrefix)
	builder.WriteString(", ")
	builder.WriteString("secret_mask_suffix=")
	builder.WriteString(ts.SecretMaskSuffix)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ts.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ts.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", ts.TeamID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ts.Name)
	builder.WriteString(", ")
	builder.WriteString("hosts=")
	builder.WriteString(fmt.Sprintf("%v", ts.Hosts))
	builder.WriteByte(')')
	return builder.String()
}

// TeamSecrets is a parsable slice of TeamSecret.
type TeamSecrets []*TeamSecret
