package keys

const (
	ApiKeyPrefix      = "e2b_"
	AccessTokenPrefix = "sk_e2b_"
	SecretPrefix      = "e2b_secret_"
)

const RootCert = `-----BEGIN CERTIFICATE-----
MIIBjzCCATWgAwIBAgIUa6uLlbKPj+Xkkh3dcoTqatV+uNEwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKcHJveHktcm9vdDAeFw0yNTA4MDIwMDEwMTFaFw0yNjA4MDIw
MDEwMTFaMBUxEzARBgNVBAMMCnByb3h5LXJvb3QwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAAQy6moqnZxY7etTlq/Ifpv3CVQM3+8NABYGa1wSWK5zgic6F4K9sqk/
o8Mb1ldU3SkGv7g+pzbzAPyK7JO5agfco2MwYTAdBgNVHQ4EFgQU/JjLmKTVJxES
aKqdC9fA7o/GzxwwHwYDVR0jBBgwFoAU/JjLmKTVJxESaKqdC9fA7o/GzxwwDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIg
cWmX/ybckN1HXrUvICq5NkI3vPvn++Sud2RzXJtB9hMCIQDwaayXxROajoG937Pp
rje/jkqPQPTNMgng1AvsgeFmkQ==
-----END CERTIFICATE-----`

const RootKey = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVDWTLVkSCdJc8W0r
TvwCR0lIQvHpkzv1UYvOJkiGahmhRANCAAQy6moqnZxY7etTlq/Ifpv3CVQM3+8N
ABYGa1wSWK5zgic6F4K9sqk/o8Mb1ldU3SkGv7g+pzbzAPyK7JO5agfc
-----END PRIVATE KEY-----`
